Vagrant.configure("2") do |config|

  #Image name
  config.vm.box = "ubuntu/bionic64"

  #Network
  config.vm.network "private_network", ip: "99.99.99.99"
  config.vm.hostname = "devbox"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #Shared folder
  config.vm.synced_folder "src/", "/src"
  config.vm.synced_folder "~/.ssh/", "/host-ssh/"

  #Inline script
  config.vm.provision "shell", path: "setup.sh"
end
