# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
    echo "Installing Docker..."
    sudo apt -y install docker.io
    echo "adding current user to docker..."
    sudo usermod -aG docker ubuntu
    date > /etc/vagrant_provisioned_at
  SCRIPT

Vagrant.configure("2") do |config|
  #This is to get rid of the error: stdin: is not a tty
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #Image name
  config.vm.box = "ubuntu/xenial64"

  #Network
  config.vm.network "private_network", ip: "99.99.99.99"
  config.vm.hostname = "devbox"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #Shared folder
  config.vm.synced_folder "src/", "/src"
  config.vm.synced_folder "~/.ssh/", "/home/vagrant/.ssh"
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

  #Inline script
  config.vm.provision "shell", inline: $script

end
