Vagrant.configure("2") do |config|
  #This is to get rid of the error: stdin: is not a tty
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.username = "ubuntu"
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  #Image name
  config.vm.box = "ubuntu/xenial64"

  #Network
  config.vm.network "private_network", ip: "99.99.99.100"
  config.vm.hostname = "devbox"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  #Shared folder
  config.vm.synced_folder "src/", "/src"
  config.vm.synced_folder "~/.ssh/", "/host-ssh/"

  #Inline script
  config.vm.provision "shell", path: "setup.sh"
end
