version: '2'
services:
  hellohttp:
    image: r1ckr/http-hello:3
    networks:
      - frontend
    ports:
      - 7777:7777

  kong:
    image: kong:2.0.0
    mem_limit: 256m
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 7946:7946
      - 7946:7946/udp
    networks:
      - frontend
    volumes:
      - /src/kong.yml:/etc/kong/kong.yml
    restart: always
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/etc/kong/kong.yml'
      KONG_LOG_LEVEL: 'info'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
  express-gateway:
    image: express-gateway:1.16.x
    mem_limit: 256m
    ports:
      - 8888:8888
      - 9876:9876
    networks:
      - frontend
    volumes:
      - /src/gateway.config.yml:/var/lib/eg/gateway.config.yml:ro
    restart: always

  nginx:
    image: nginx:1.17
    mem_limit: 256m
    ports:
      - 9999:9999
    networks:
      - frontend
    volumes:
      - /src/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hellohttp

networks:
  frontend:

volumes:
  db-data: