version: "2"
services:
  hellohttp:
    image: r1ckr/http-hello:latest
    networks:
      - frontend
    ports:
      - 7777:7777
    environment:
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_TOOL_OPTIONS: "-Xmx512m"

  kong:
    image: kong:latest
    mem_limit: 256m
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 7946:7946
      - 7946:7946/udp
    networks:
      - frontend
    volumes:
      - /src/kong.yml:/etc/kong/kong.yml:ro
    restart: always
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/etc/kong/kong.yml'

  express-gateway:
    image: express-gateway:latest
    mem_limit: 128m
    ports:
      - 8888:8888
      - 9876:9876
    networks:
      - frontend
    volumes:
      - /src/gateway.config.yml:/var/lib/eg/gateway.config.yml:ro
    restart: always

  nginx:
    image: nginx:latest
    mem_limit: 128m
    ports:
      - 9999:9999
    networks:
      - frontend
    volumes:
      - /src/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hellohttp

networks:
  frontend:

volumes:
  db-data: