#cloud-config

coreos:
  update:
    reboot-strategy: "etcd-lock"
    group: stable
    server: {{UPDATE_URL}}
  etcd2:
    name: {{ETCD_NODE_NAME}}
    initial-cluster: {{ETCD_INITIAL_CLUSTER}}
    advertise-client-urls: http://$private_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://0.0.0.0:2380
  units:
  - name: etcd2.service
    command: start
  - name: flanneld.service
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
    command: start

      