#cloud-config
coreos:
  update:
    reboot-strategy: "etcd-lock"
  etcd2:
    proxy: on
    initial-cluster: ETCD_INITIAL_CLUSTER
    listen-client-urls: http://0.0.0.0:2379
  locksmith:
    group: "worker"
    window-start: Mon 9:00
    window-length: 1h
  units:
    - name: etcd2.service
      command: start
    - name: kube-etcd.service
      command: start
      content: |
        [Unit]
        Description=etcd cluster for Kubernetes
        After=docker.service
        Requires=docker.service
        [Service]
        Restart=on-failure
        RestartSec=20
        TimeoutStartSec=60
        RemainAfterExit=yes
        ExecStartPre=-/usr/bin/docker stop kube-etcd
        ExecStartPre=-/usr/bin/docker rm kube-etcd
        ExecStartPre=/usr/bin/docker pull gcr.io/google-containers/etcd:3.0.17
        ExecStart=/usr/bin/docker run --name kube-etcd \
          --net=host \
          --volume=/var/etcd-data:/etcd-data \
          gcr.io/google-containers/etcd:3.0.17 \
          /usr/local/bin/etcd \
          --data-dir=/etcd-data --name NODE_NAME \
          --initial-advertise-peer-urls http://PRIVATE_IPV4:2390 \
          --listen-peer-urls http://0.0.0.0:2390 \
          --advertise-client-urls http://PRIVATE_IPV4:2389 \
          --listen-client-urls http://0.0.0.0:2389 \
          --initial-cluster "KUBE_INITIAL_ETCD_CLUSTER"
        ExecStop=/usr/bin/docker stop kube-etcd
        ExecStop=/usr/bin/docker rm kube-etcd
        [Install]
        WantedBy=multi-user.target