$script = <<-SCRIPT
    echo "Installing Docker..."
    sudo apt-get update
    sudo apt -y install docker.io

    echo "Adding current user to docker..."
    sudo usermod -aG docker ubuntu

    date > /etc/vagrant_provisioned_at
  SCRIPT

Vagrant.configure("2") do |config|

  #This is to get rid of the error: stdin: is not a tty
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", inline: $script

  (1..3).each do |i|
    config.vm.define "minio#{i}" do |node|
      node.vm.network "private_network", ip: "192.167.201.10#{i}"
      node.vm.synced_folder "data#{i}/", "/data", create: true
      node.vm.provision "shell",
        inline: "echo hello from node #{i}"
    end
  end
end
