ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  #This is to get rid of the error: stdin: is not a tty
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "setup.sh"

  (1..4).each do |i|
    config.vm.define "minio#{i}" do |node|
      node.vm.network "private_network", ip: "192.167.201.10#{i}"
      node.vm.synced_folder "data#{i}/", "/data", create: true
      node.vm.hostname = "minio#{i}"
      node.vm.provision "shell",
        inline: "echo hello from node #{i}"
    end
  end
end
