ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  #This is to get rid of the error: stdin: is not a tty
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #VM settings
  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 2
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "setup.sh"

  #Adding my own id_rsa key into the authorized_keys file
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/ubuntu/.ssh/me.pub"
  config.vm.provision "shell", inline: "cat /home/ubuntu/.ssh/me.pub >> /home/ubuntu/.ssh/authorized_keys"

  (1..3).each do |i|
    # Adding each hostname into the hosts file of each VM (Don't judge :D)
    config.vm.provision "shell", inline: "echo 192.167.200.10#{i} node#{i} >> /etc/hosts"
    config.vm.define "node#{i}" do |node|
      node.vm.network "private_network", ip: "192.167.200.10#{i}"
      node.vm.synced_folder "data#{i}/", "/data", create: true
      node.vm.hostname = "node#{i}"
      node.vm.provision "shell",
        inline: "echo #{i} is ready to rock!"
    end
  end
end
